lib/ash_admin/components/resource/form.ex
When we had nested form under direct_control, configured like so:
```
create :create do
primary? true
...
argument :competencies, {:array, :map}
...
change manage_relationship(:competencies, :competencies, type: :direct_control)
end
```
When the form was submitted with errors we got the following
```elixir
** (FunctionClauseError) no function clause matching in Keyword.split/2
(elixir 1.13.3) lib/keyword.ex:1102: Keyword.split("form[competencies][0]", [:format, :for_path])
(ash_phoenix 0.7.2-rc.1) lib/ash_phoenix/form/form.ex:316: AshPhoenix.Form.validate_opts_with_extra_keys/2
(ash_phoenix 0.7.2-rc.1) lib/ash_phoenix/form/form.ex:1327: AshPhoenix.Form.errors/2
(ash_admin 0.4.5-rc.0) lib/ash_admin/components/resource/form.ex:282: anonymous fn/3 in …
```
=> fix: failing error case for nested forms

lib/ash_admin/components/resource/table.ex
This blows up for relationships, where the `attribute.type` is something like `:belongs_to` (instead of a module name like `Ash.Type.String`), meaning that relationships are always rendered as `...`.
Fixes issue caused by
https://github.com/ash-project/ash/commit/6aa0c0b591576c26327149e95cbbcc42611cff6d#diff-dd4491b1dc2629842f30d2edee72161d609bc73dff8e10a3b3e61f60b4ffc756L176-R177
I'm not sure if this is the best place to fix it (or if the issue may affect other things within Ash), but I noticed it while using ash_admin so thought I'd fix it here!
=> Skip check for embedded types when rendering attributes

.github/workflows/elixir.yml
The changelog URL in the auto release tweet was pointing at ash_phoenix, now correctly points at ash_admin
=> fix: changelog URL in release tweet

lib/ash_admin/components/resource/form.ex, lib/ash_admin/components/resource/show.ex, lib/ash_admin/components/resource/table.ex
I noticed while starting to work with binary blobs of data, that admin would happily try to render them - 
And then cowboy would crash in a loop - 
```
[error] Ranch listener AppName.Endpoint.HTTP had connection process started with 
:cowboy_clear:start_link/4 at #PID<0.1167.0> exit with reason: {%Jason.EncodeError{message: 
"invalid byte 0xFF in <<255, 216, 255, 224, ...
```
Same when editing the records 😭 
This is some super-quick fixes to stop that from happening - italic text is used to represent the attribute contents that shouldn't be displayed or edited as-is.
=> fix: Binary data display

.formatter.exs
This variable was renamed, but references to it were not.
The previous version gave the error:
```
$ mix format --check-formatted
warning: variable "locals_without_parens" does not exist and is being expanded to "locals_without_parens()", please use parentheses to remove the ambiguity or change the variable name
deps/ash_admin/.formatter.exs:25
** (CompileError) deps/ash_admin/.formatter.exs:25: undefined function locals_without_parens/0 (there is no such import)
```
=> fix: Fix `undefined function locals_without_parens/0` error

.github/ISSUE_TEMPLATE/bug_report.md
=> chore: fix markdown in the bug report template

README.md, lib/ash_admin/templates/admin.html.eex, mix.exs
I ran into an issue where inline styles provided by AshAdmin were being blocked by the CSP set for our app, and after a bit of research I found that you can specify nonces on specific inline CSS/JS blocks to allow them to be executed. 
Source: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
So I've added nonces to the blocks for the main CSS/JS content, updated the CSP in my app that uses AshAdmin, and presto, it works again!
(Note: There are still some CSP violations, for the markdown editor/JSON editor also loaded in the admin layout - as they are truly external files I didn't want to touch them here.)
=> feat: Inline style nonce

lib/ash_admin/pages/page_live.ex, lib/ash_admin/router.ex, test/page_live_test.exs, test/support/router.ex
Fixing issue https://github.com/ash-project/ash_admin/issues/45
Came up with an initial idea for now how we can do it but `ash_admin/2` can't be called from within the `call/2`
=> fix: Admin links are not aware of the scope where ash_admin is called

config/config.exs
This doesn't seem needed anymore, when running the project, it says it's the following:
You have configured application :tails in your configuration file,
but the application is not available.
This usually means one of:
1. You have not added the application as a dependency in a mix.exs file.
2. You are configuring an application that does not really exist.
Please ensure :tails exists or remove the configuration.
=> Remove config :tails

dev/repo/seeds.exs, mix.exs
@zachdaniel these seeds only include `User`, `Customer`, `Organization` and `Ticket`.
I couldn't add `Comment` because it is polymorphic, I am investigaring it.
Please let me know if it is possible improve it any way, thanks
=> feat: Add seed with Admin, User, Customer, Organization and Ticket

lib/ash_admin/components/resource/form.ex
Seems like there has been a regression when removing surface.
Without these fixes I can't successfully load a create form when the form has a relationship
=> fix(create-form): errors from removal of surface

lib/ash_admin/components/top_nav/tenant_form.ex
Adds a label for the Tenant in the Top Nav, moves the X icon to the right and uses the same X icon as Actor.
Before:
After:
=> UI consistency in top nav

lib/ash_admin/components/top_nav/tenant_form.ex
```
lib/ash_admin/components/top_nav/tenant_form.ex:40:guard_fail
The guard clause:
when _ :: <<_::8, _::size(1)>> === nil
can never succeed.
```
=> fix dialyzer warning in top nav tenant form

lib/ash_admin/components/resource/form.ex
This code improve how ash admin shows selectbox, currently it is impossible to set `nil` the resource's attrs even `allow_nil?` is true, another issue is when you have a attr that doesn't allow nil but has default equals to nil Phoenix.HTML.Form.select automatically select first option on the selectbox live view doesn't receive the event, issue reported here #65
=> Add prompt to selectbox

lib/ash_admin/components/resource/data_table.ex, lib/ash_admin/components/resource/table.ex
I noticed that relationships were displayed in tables with None when policies were set for the foreign resource. It seems that the actor wasn't passed when loading the resource. This PR fixes just that.
=> Pass actor when fetching relationships attributes

lib/ash_admin/components/resource/form.ex
Fixes a bug where boolean attributes with a `false` value don't get set in the select field.
=> fix: Allow showing false values for boolean select inputs

lib/ash_admin/components/resource/form.ex
input, this seems to fix it bypassing the rrror and successfully showing the input
=> fix: {:array, type} attributes return error `no nil values` and not

lib/ash_admin/components/resource/form.ex
Pass `tenant` to `Changeset.for_*` instead of `Changeset.set_tenant` so that `change` modules can get it from `context`.
=> fix: pass tenant to `Changeset.for_*` directly

lib/ash_admin/actor_plug/plug.ex
Starting to use ash admin. Was looking into how it plays with authorization when saw:
```elixir
|> Plug.Conn.assign(:authorizing, authorizing || false)
|> Plug.Conn.assign(:actor_paused, actor_paused)
|> Plug.Conn.assign(:authorizing, authorizing)
```
And other small things. Fixed those and end up refactoring the file.
I'm not sure that this file is actually supposed to be used by people since it has `@moduledoc false`, but anyway.
Questions:
1) What's the plan for this Plug (will get public or removed maybe)?
1) Why there is no `:ash` in formatter `import_deps`?
1) Am I right in understanding that by default all admins are equal as authorization rules do not apply to them (unless they use ability to act as some other actor)?
=> fix: small refactor in actor plug

assets/js/app.js
It looks to me that the cookie tracking `actor_tenant` added in #100 wasn't being properly cleared when clearing the actor with `clear_actor`. This PR adds a suspectedly missing `=` when setting `actor_tenant` so that the cookie is properly (?) cleared.
Maybe the same is true for the `actor_action`?
I couldn't see that this was under testing.
First code PR ever so be kind 🙏🏼
=> fix: clear actor_tenant cookie when clearing actor

README.md, documentation/dsls/DSL:-AshAdmin.Resource.md, documentation/tutorials/contributing-to-ash-admin.md, documentation/tutorials/getting-started-with-ash-admin.md, lib/ash_admin/resource/resource.ex, mix.exs
* Moved main README contents into a Getting Started tutorial
* Separated out Contributing into its own small tutorial
* Minor tweaks to DSL documentation
(I don't have permission to do this)
=> docs: Rewrite docs for consistent format with other Ash packages

documentation/dsls/DSL-AshAdmin.Domain.md, lib/ash_admin/components/top_nav.ex, lib/ash_admin/components/top_nav/helpers/dropdown_helper.ex, lib/ash_admin/domain.ex, test/components/top_nav/helpers/dropdown_helper_test.exs, test/support/domain.ex, test/support/resources/blog.ex
Let's say, we have this in a domain:
```elixir
admin do
show? true
resource_group_labels group_b: "Group B", group_a: "Group A", group_c: "Group C"
end
``` 
Currently, `resource_group_labels` shows labels in ascending alphabetical order and this will result to this in the domain dropdown:
- Group A
- Group B
- Group C
- (resources without group)
This PR let `resource_group_labels` to strictly sort labels as given and this will be the result in the domain dropdown:
- Group B
- Group A
- Group C
- (resources without group)
The reason is that when I tried `ash_admin` with `ash_paper_trail`, I tried to group all resources with `Version` in a group called `Audit log` which starts with an `A`. There is another group called `Domain`. As result, `Audit log` group is always at the top and I wanted …
=> feat: Sort resource_group_labels by given order

lib/ash_admin/components/resource/data_table.ex, lib/ash_admin/components/resource/form.ex, lib/ash_admin/components/resource/generic_action.ex
This PR removes warnings related to `params` of `AshPhoenix.Form.submit`:
As reminder, the warning was the following:
```elixir
warning: The `params` option should be supplied at all times. This will be required in a future major release.
To silence this warning without providing `params`, you can pass `params: nil`.
For example:
def handle_event("submit", %{"form" => params}, socket) do
case AshPhoenix.Form.submit(socket.assigns.form, params: params) do
...
end
end
``` 
The form unassigned parameters are given to `AshPhoenix.Form.submit` when possible, otherwise `params: nil` is given.
=> chore: Fix warnings related to params of AshPhoenix.Form.submit

dev/resources/accounts/resources/user.ex, lib/ash_admin/components/resource/form.ex, lib/ash_admin/components/resource/show.ex
This PR has 2 fixes:
- Show calculation form even when calcuation doesn't have arguments, we are no preload any calculation, because that we should show at least the calculate button to load it
- Show warning message on embedded calculation's argument, until we don't support embedded type on `FilterForm` (see here https://github.com/ash-project/ash_phoenix/blob/v2.1.9/lib/ash_phoenix/filter_form/filter_form.ex#L1246) I think should be good to at least show this warning, what do you think?
=> fix(Calculations): Show form when calculation doesn't have arguments

assets/tailwind.config.js, lib/ash_admin/components/core_components.ex, lib/ash_admin/components/resource/form.ex, mix.exs, priv/static/assets/app.css, priv/static/assets/app.js
I removed `phx-feedback-for` and replace to `Phoenix.Component.used_input?`, see more here https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md
I tried to filter the unsued params from `list_value/1` or `render_fallback_attribute/7` but I wasn't able to do it, because the form is been updated on `AshPhoenix.Form.validate/3` before we receive the attributes.
The only solution I got is filtering the params before validate it or updating `ash_phoenix` to handle `_unsued_*`
I will keep it as draft until we got a better solution
=> fix(PhoenixLiveView): remove phx-feedback-for and fix unsued params

lib/ash_admin/components/resource/form.ex
We can't use `Map.new/2` on `replace_unused/1` because we must remove the `_unused_*` attributes
=> fix(UnsuedParams): Filter nil values

lib/ash_admin/components/resource/resource.ex, lib/ash_admin/pages/page_live.ex
- get primary read action for resource loading from Ash.Resource.Info, with a fallback to AshAdmin.Helpers
- display and log error in the case where the primary read action produces an error
=> guard against problematic primary read action configurations (#255)

README.md, documentation/tutorials/getting-started-with-ash-admin.md
Security tutorial added, based on Zach's reply to this thread:
https://elixirforum.com/t/ash-admin-inside-ash-authenticated-live-session/65213/3
I'm not sure if this is still the recommended way, but it didn't seem the ash_admin macro is compatible with the ash_authentication_live_session macro so I assume it is; please do correct me if I'm wrong :))
A line was also removed from README.md, asking users to use different ash_admin branch with LiveView >= 1.0
=> Add security section to tutorial

mix.exs
- points to proper migration-path
- --drop-columns was not a working option, assume this meant dont-drop-columns
- [no] Bug fixes include regression tests
- [no] Features include unit/acceptance tests
=> fix generate_migrations alias

lib/ash_admin/components/resource/form.ex, lib/ash_admin/components/resource/relationship_field.ex
Playing around with ash admin on my project and I noticed I'm missing a close button for the forms.
=> feat: implement close button for form

lib/ash_admin/components/resource/metadata_table.ex, lib/ash_admin/components/resource/show.ex
Bug fixes for better managing cross-domain relationships. The bugs where that we didn't use the correct `domain` in the links when navigating to another resource.
This PR uses `Ash.Resource.Info.domain(relationship.destination)` to solve the issue.
I setup a test-project and clicked around to ensure that it didn't break anything 🙆‍♂️
=> fix: Handle cross-domain links

.formatter.exs, .github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/proposal.md, .github/PULL_REQUEST_TEMPLATE.md, dev/resources/tickets/resources/customer.ex, dev/resources/tickets/resources/ticket/ticket.ex, documentation/dsls/DSL-AshAdmin.Resource.md, lib/ash_admin/components/resource/form.ex, lib/ash_admin/resource/field.ex, lib/ash_admin/resource/resource.ex, lib/ash_admin/resource/verifiers/verify_file_arguments_exist.ex
There are a couple options for file uploads that are currently hardcoded that would be useful to expose. For example, it would be nice to be able to upload files larger than 8 megabytes. 
I've adjusted the AshAdmin DSL to allow for specifying `max_file_size` in bytes and `accepted_extensions` for what type of files to allow uploading. These options are passed directly to the LiveView [allow_upload](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#allow_upload/3) call and mirror it's documentation.
I've also added a verify step to the AshAdmin DSL to ensure that an argument with these new file options exist in an action of the resource.
=> feature: add upload options for `Ash.Type.File` arguments

lib/ash_admin/components/resource/show.ex
Hey,
I've seen a bunch of error logs like the following:
```
Failed to display value:
** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for type Postgrex.Range (a struct). This protocol is implemented for the following type(s): Ash.CiString, Ash.NotLoaded, Atom, BitString, Date, DateTime, Decimal, Float, Integer, List, NaiveDateTime, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Time, Tuple, URI
Got value:
%Postgrex.Range{
lower: ~U[2025-05-26 08:53:35.314461Z],
upper: :unbound,
lower_inclusive: true,
upper_inclusive: false
}
(phoenix_html 4.2.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
(phoenix_html 4.2.1) lib/phoenix_html/safe.ex:15: …
```
=> Change level of repetitive log

assets/js/app.js, lib/ash_admin/components/layouts.ex
#350 
Leave anything that you believe does not apply unchecked.
=> Read phoenix js assests at compile time

lib/ash_admin/pages/page_live.ex
In the process of working with a resource with soft delete functionality, I've noticed the [documented](https://github.com/ash-project/ash_admin/blob/main/documentation/dsls/DSL-AshAdmin.Resource.md#admin-show_action) DSL `admin.show_action` option wasn't actually being used when showing a single record, so here's a quick fix.
Leave anything that you believe does not apply unchecked.
=> fix: use `admin.show_action` when viewing a single record
